### ISSUE TITLE
The system cannot find the file specified

### ISSUE THREAD

**Issue by WobbyChip** [javedali99/audio-to-text-transcription#2]
C:\Users\WobbyChip\Desktop\audio-to-text-transcription-main>python youtube_audio_to_text.py
Enter the YouTube video URL: https://www.youtube.com/watch?v=23Vz7swrocg
Audio downloaded to YoutubeAudios/audio.mp3
100%|███████████████████████████████████████| 139M/139M [00:06<00:00, 23.6MiB/s]
C:\Users\WobbyChip\AppData\Local\Programs\Python\Python39\lib\site-packages\whisper\transcribe.py:115: UserWarning: FP16 is not supported on CPU; using FP32 instead
  warnings.warn("FP16 is not supported on CPU; using FP32 instead")
Traceback (most recent call last):
  File "C:\Users\WobbyChip\Desktop\audio-to-text-transcription-main\youtube_audio_to_text.py", line 46, in <module>
    result = model.transcribe("YoutubeAudios/audio.mp3")
  File "C:\Users\WobbyChip\AppData\Local\Programs\Python\Python39\lib\site-packages\whisper\transcribe.py", line 122, in transcribe
    mel = log_mel_spectrogram(audio, model.dims.n_mels, padding=N_SAMPLES)
  File "C:\Users\WobbyChip\AppData\Local\Programs\Python\Python39\lib\site-packages\whisper\audio.py", line 140, in log_mel_spectrogram
    audio = load_audio(audio)
  File "C:\Users\WobbyChip\AppData\Local\Programs\Python\Python39\lib\site-packages\whisper\audio.py", line 58, in load_audio
    out = run(cmd, capture_output=True, check=True).stdout
  File "C:\Users\WobbyChip\AppData\Local\Programs\Python\Python39\lib\subprocess.py", line 501, in run
    with Popen(*popenargs, **kwargs) as process:
  File "C:\Users\WobbyChip\AppData\Local\Programs\Python\Python39\lib\subprocess.py", line 947, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\WobbyChip\AppData\Local\Programs\Python\Python39\lib\subprocess.py", line 1416, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] The system cannot find the file specified

**Comment by WobbyChip** [comment]
This worked:

[InstallFfmpeg.zip](https://github.com/javedali99/audio-to-text-transcription/files/13629001/InstallFfmpeg.zip)
