### ISSUE TITLE
Detecting wrong language and Unicode error

### ISSUE THREAD

**Issue by AnkitChandwada007** [javedali99/audio-to-text-transcription#3]
The youtube video is in 98% Hindi along with some english words. 
I am getting this error while trying to do transcription.

![error](https://github.com/javedali99/audio-to-text-transcription/assets/118892662/b57c4da2-f9a5-49e4-afaa-7e29aa305171)

Detected language: ur
Traceback (most recent call last):
  File "C:\Users\geeky\OneDrive\Desktop\YT Transcribe\youtube_audio_to_text.py", line 55, in <module>
    create_and_open_txt(transcribed_text, f"output_{language}.txt")
  File "C:\Users\geeky\OneDrive\Desktop\YT Transcribe\youtube_audio_to_text.py", line 24, in create_and_open_txt
    file.write(text)
  File "C:\Users\geeky\anaconda3\envs\yt\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode characters in position 1-5: character maps to <undefined>

**Comment by AnkitChandwada007** [comment]
Is their any way to specify language manually? Beacuse hindi and urdu are very similar when spoken but they have different writing script Devanagari & Arabic respectively.
