### ISSUE TITLE
FileNotFoundError: [WinError 2] The system cannot find the file specified _winapi.CreateProcess(executable, args,

### ISSUE THREAD

**Issue by wutpppppppppppppppppp** [javedali99/audio-to-text-transcription#5]
I got this error message when I was trying to transcript the audio. How do I fix this?
`D:\Study\audio-to-text-transcription\audiovenv\Lib\site-packages\whisper\transcribe.py:126: UserWarning: FP16 is not supported on CPU; using FP32 instead
  warnings.warn("FP16 is not supported on CPU; using FP32 instead")
Traceback (most recent call last):
  File "D:\Study\audio-to-text-transcription\youtube_audio_to_text.py", line 46, in <module>
    result = model.transcribe("YoutubeAudios/audio.mp3")
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Study\audio-to-text-transcription\audiovenv\Lib\site-packages\whisper\transcribe.py", line 133, in transcribe
    mel = log_mel_spectrogram(audio, model.dims.n_mels, padding=N_SAMPLES)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Study\audio-to-text-transcription\audiovenv\Lib\site-packages\whisper\audio.py", line 140, in log_mel_spectrogram
    audio = load_audio(audio)
            ^^^^^^^^^^^^^^^^^
  File "D:\Study\audio-to-text-transcription\audiovenv\Lib\site-packages\whisper\audio.py", line 58, in load_audio
    out = run(cmd, capture_output=True, check=True).stdout
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\woosh\AppData\Local\Programs\Python\Python312\Lib\subprocess.py", line 548, in run       
    with Popen(*popenargs, **kwargs) as process:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\woosh\AppData\Local\Programs\Python\Python312\Lib\subprocess.py", line 1026, in __init__ 
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\woosh\AppData\Local\Programs\Python\Python312\Lib\subprocess.py", line 1538, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [WinError 2] The system cannot find the file specified`
![Untitled](https://github.com/javedali99/audio-to-text-transcription/assets/99638489/1230c790-4d5a-440f-a47b-4d652321f989)

**Comment by whisnumurtyga** [comment]
bruh @wutpppppppppppppppppp  are you have trying run code in same directory where you install conda?

**Comment by Ruinan-Ding** [comment]
you must add ffmpeg to your environment variables

**Comment by Ruinan-Ding** [comment]
https://www.gyan.dev/ffmpeg/builds/
